{{- if and .Values.secrets.enabled .Values.secrets.keys }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "andino.name" . }}-secrets
  namespace: {{ include "andino.namespace" . }}
  labels:
    {{- include "andino.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "andino.name" . }}-paramstore
    kind: SecretStore
  target:
    name: {{ include "andino.name" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.secrets.keys }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
    {{- end }}
{{- end }}
