{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "andino.name" . }}-paramstore
  namespace: {{ include "andino.namespace" . }}
  labels:
    {{- include "andino.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.secrets.region | default "us-east-1" }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "andino.serviceAccountName" . }}
{{- end }}
